### ISSUE TITLE
Semantic Segmantion Classes

### ISSUE THREAD

**Issue by YanivKatz** [SysCV/shift-dev#4]
Can you please add a txt/yaml file containing the classes used for semantic segmentation and their indices?

**Comment by waychin-weiqin** [comment]
Hi @YanivKatz, as the authors generated this dataset using Carla, I managed to find all the information about the classes and their indices for semantic segmentation from the [Carla documentation page](https://carla.readthedocs.io/en/latest/ref_sensors/#semantic-segmentation-camera).

**Comment by mattiasegu** [comment]
Thanks @waychin-weiqin for replying first! That is indeed correct.

To make it easy for everyone, we will also provide a file with the classes and indices used for semantic segmentation.

Leaving this issue open until then.

**Comment by HRHLALALA** [comment]
Hi @suniique , I found that some videos have unexpected pixel id of 23. Can you help double check that ? Thanks

In 0ec5-f0e2.mp4:

```
>>> np.unique(frame)
array([ 0,  1,  3,  4,  7,  9, 10, 11, 13, 19, 20, 23], dtype=uint8)
```

**Comment by suniique** [comment]
hey @HRHLALALA, thanks for the question! Yes, the decompressing of video sequences does require many environment settings, otherwise, you may not get exactly the same results. To simply that, we have released all the sematic segmentation labels in the plan zip files of PNGs.   

You can download them on our server, for example, the `semseg.zip` under
https://dl.cv.ethz.ch/shift/continuous/videos/1x/train/front/
